/**
*Load module dependecies
*/
var express = require('express');
/**
*Load local module dependecies
*/
var fareController = require('../controllers/fare');

var router = express.Router();
// ------------------------------------------------------------------------------------------
// Fare Success Response
// ------------------------------------------------------------------------------------------
/**
 * @apiDefine FareSuccess
 * @apiParam {Object} _id      A Unique id of Fare document
 * @apiParam {Object} from     The starting/source fare id
 * @apiParam {Object} to       The  ending/destination fare id
 * @apiParam {String} route    The route where the passenger want to travel
 * @apiParam {Number} distance The distance between the two fares
 * @apiParam {Number} fare     The price required to travel between these two sations
*/
// ------------------------------------------------------------------------------------------
// Invalid Fare Id Response
// ------------------------------------------------------------------------------------------
/**
* @apiDefine InvalidFareIdError
* @apiVersion 0.1.0
*
* @apiErrorInvalidFareId InvalidFareId Valid Fare Id 24 by mongodb autogenerated generated Id
*
* @apiErrorExample  Invalid-Fare-Id-Response:
* HTTP 400 Bad request
*{
    "message": "Train Fare Id is not valid"
}
*
*/
// ------------------------------------------------------------------------------------------
// Fare Not Found Error Response
// ------------------------------------------------------------------------------------------
/**
* @apiDefine FareNotFoundError
* @apiVersion 0.1.0
*
* @apiErrorFareNotFound FareNotFound Error generated if Fare not found
*
* @apiErrorExample  Fare-Not-Found-Response:
** HTTP 400 Bad request
*{
*    "message": "No maching document found."
*}
*
*/
// ------------------------------------------------------------------------------------------
// Server Error Response
// ------------------------------------------------------------------------------------------
/**
* @apiDefine InternalServerError
* @apiVersion 0.1.0
*
* @apiErrorInternalServerError InternalServerError Error response for internal server errors
*
* @apiErrorExample  Internal-Server-Error-Response:
** HTTP 500 Bad request
*{
*    "message": "Internal Server Error."
*}
*
*/

/**
 * @apiDefine FareCreationSuccess
 * @apiParam(Success 201)  {Object} _id      A Unique id of Fare document
 * @apiParam(Success 201)  {Object} from     The starting/source fare id
 * @apiParam(Success 201)  {Object} to       The  ending/destination fare id
 * @apiParam(Success 201)  {String} route    The route where the passenger want to travel
 * @apiParam(Success 201)  {Number} distance The distance between the two fares
 * @apiParam(Success 201)  {Number} fare     The price required to travel between these two sations
*/
// ------------------------------------------------------------------------------------------
// Current Permissions.
// ------------------------------------------------------------------------------------------
/**
 * @apiDefine UnauthorizedError
 * @apiVersion 0.1.0
 *
 * @apiError Unauthorized Only authenticated users can access the endpoint.
 *
 * @apiErrorExample  Unauthorized-Error-Response:
 *     HTTP 401 Unauthorized
 *     {
 *      "message":"Access forbidden"
 *     }
 */

/**
 * @api {POST} /fares/ Create Fare
 * @apiName postFare
 * @apiGroup Fare
 * @apiDescription Create a new Fare
 * @apiVersion 0.1.0
 *

 * @apiParam {Object} _id      A Unique id of Fare document
 * @apiParam {Object} from     The starting/source fare id
 * @apiParam {Object} to       The  ending/destination fare id
 * @apiParam {String} route    The route where the passenger want to travel
 * @apiParam {Number} distance The distance between the two fares
 * @apiParam {Number} fare     The price required to travel between these two sations
 *
 * @apiUse FareCreationSuccess
 *
 * @apiParamExample {json} Request-Example
 *
 * {"from":"5a74264fc461a418b08dae01",
 * "to":"5a7455be8e130d47c86a03f6",
 * "distance":1092,
 * "route":"EW"
 * }
 *
 * @apiSuccessExample Response-Success-Example
 *HTTP 200 OK
 *{
 *    "_id": "5a96981b3993840b742ab7b5",
 *    "from": "5a74264fc461a418b08dae01",
 *    "to": "5a7455be8e130d47c86a03f6",
 *    "userId": "5a8157014d99ed52700bc99f",
 *    "distance": 1092,
 *    "fare": 0.4095
 * }
 *@apiUse UnauthorizedError
 @apiUse InternalServerError
 */
router.post('/', fareController.create);
/**
 * @api {GET} /fares/ Find all fares
 * @apiName FindAllFares
 * @apiGroup Fare
 * @apiDescription List all registerd Fares
 * @apiVersion 0.1.0
 *
 * @apiUse FareSuccess
 *
 * @apiSuccessExample{json} Response-Success-Example
  *
  *HTTP 200 OK
  {
    "total number of fare documents": 41,
    "fares": [
        {
            "_id": "5a8590e0c7abd121e4b3e535",
            "from": {
                "_id": "5a83fa1b1104c34bd8a66e72",
                "name": "Abo Junction",
                "route": "NS"
            },
            "to": {
                "_id": "5a83fa591104c34bd8a66e74",
                "name": "Saris",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 840,
            "fare": 0.315
        },
        {
            "_id": "5a85933d615a3a47c831f311",
            "from": {
                "_id": "5a83fa591104c34bd8a66e74",
                "name": "Saris",
                "route": "NS"
            },
            "to": {
                "_id": "5a83fa851104c34bd8a66e76",
                "name": "Adey Abeba",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 540,
            "fare": 0.2025
        },
        {
            "_id": "5a8593c408ea5b545c02bcb1",
            "from": {
                "_id": "5a83fa851104c34bd8a66e76",
                "name": "Adey Abeba",
                "route": "NS"
            },
            "to": {
                "_id": "5a8415aa542c19147c03c52e",
                "name": "Nefas Silik 1",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 995,
            "fare": 0.373125
        },
        {
            "_id": "5a8593ed0311323b90e037d0",
            "from": {
                "_id": "5a8415aa542c19147c03c52e",
                "name": "Nefas Silik 1",
                "route": "NS"
            },
            "to": {
                "_id": "5a8415c0542c19147c03c52f",
                "name": "Nefas Silik 2",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 861,
            "fare": 0.322875
        },
        {
            "_id": "5a85943d0311323b90e037d1",
            "from": {
                "_id": "5a8415c0542c19147c03c52f",
                "name": "Nefas Silik 2",
                "route": "NS"
            },
            "to": {
                "_id": "5a8415d5542c19147c03c530",
                "name": "Lancha",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 1972,
            "fare": 0.7395
        },
        {
            "_id": "5a859575ab99be23d4ec1370",
            "from": {
                "_id": "5a8415d5542c19147c03c530",
                "name": "Lancha",
                "route": "NS"
            },
            "to": {
                "_id": "5a8415f6542c19147c03c531",
                "name": "Riche",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 555,
            "fare": 0.208125
        },
        {
            "_id": "5a85959dab99be23d4ec1371",
            "from": {
                "_id": "5a8415f6542c19147c03c531",
                "name": "Riche",
                "route": "NS"
            },
            "to": {
                "_id": "5a84160a542c19147c03c532",
                "name": "Meshawalekya",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 610,
            "fare": 0.22875
        },
        {
            "_id": "5a8595a6ab99be23d4ec1372",
            "from": {
                "_id": "5a84160a542c19147c03c532",
                "name": "Meshawalekya",
                "route": "NS"
            },
            "to": {
                "_id": "5a84161b542c19147c03c533",
                "name": "Stadium",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 481,
            "fare": 0.180375
        },
        {
            "_id": "5a8595b9ab99be23d4ec1373",
            "from": {
                "_id": "5a84161b542c19147c03c533",
                "name": "Stadium",
                "route": "NS"
            },
            "to": {
                "_id": "5a841626542c19147c03c534",
                "name": "Leghar",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 908,
            "fare": 0.3405
        },
        {
            "_id": "5a8595c3ab99be23d4ec1374",
            "from": {
                "_id": "5a841626542c19147c03c534",
                "name": "Leghar",
                "route": "NS"
            },
            "to": {
                "_id": "5a841635542c19147c03c535",
                "name": "Mexico",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 435,
            "fare": 0.163125
        },
        {
            "_id": "5a8595ccab99be23d4ec1375",
            "from": {
                "_id": "5a841635542c19147c03c535",
                "name": "Mexico",
                "route": "NS"
            },
            "to": {
                "_id": "5a841677542c19147c03c536",
                "name": "Tegbared",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 569,
            "fare": 0.213375
        },
        {
            "_id": "5a859609ab99be23d4ec1376",
            "from": {
                "_id": "5a841677542c19147c03c536",
                "name": "Tegbared",
                "route": "NS"
            },
            "to": {
                "_id": "5a841692542c19147c03c537",
                "name": "St Lideta",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 691,
            "fare": 0.259125
        },
        {
            "_id": "5a859613ab99be23d4ec1377",
            "from": {
                "_id": "5a841692542c19147c03c537",
                "name": "St Lideta",
                "route": "NS"
            },
            "to": {
                "_id": "5a84169c542c19147c03c538",
                "name": "Darmar",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 733,
            "fare": 0.274875
        },
        {
            "_id": "5a859624ab99be23d4ec1378",
            "from": {
                "_id": "5a84169c542c19147c03c538",
                "name": "Darmar",
                "route": "NS"
            },
            "to": {
                "_id": "5a8416a6542c19147c03c539",
                "name": "Abnet",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 591,
            "fare": 0.221625
        },
        {
            "_id": "5a859631ab99be23d4ec1379",
            "from": {
                "_id": "5a8416a6542c19147c03c539",
                "name": "Abnet",
                "route": "NS"
            },
            "to": {
                "_id": "5a8416b1542c19147c03c53a",
                "name": "Sebategna",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 744,
            "fare": 0.279
        },
        {
            "_id": "5a859646ab99be23d4ec137a",
            "from": {
                "_id": "5a8416b1542c19147c03c53a",
                "name": "Sebategna",
                "route": "NS"
            },
            "to": {
                "_id": "5a8416bd542c19147c03c53b",
                "name": "Autobus Tera",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 861,
            "fare": 0.322875
        },
        {
            "_id": "5a8596df6cc7600e089a86d3",
            "from": {
                "_id": "5a8416bd542c19147c03c53b",
                "name": "Autobus Tera",
                "route": "NS"
            },
            "to": {
                "_id": "5a8416cc542c19147c03c53c",
                "name": "Gojam Berenda",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 612,
            "fare": 0.2295
        },
        {
            "_id": "5a8596eb6cc7600e089a86d4",
            "from": {
                "_id": "5a8416cc542c19147c03c53c",
                "name": "Gojam Berenda",
                "route": "NS"
            },
            "to": {
                "_id": "5a8416d6542c19147c03c53d",
                "name": "Atikilit Tera",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 608,
            "fare": 0.228
        },
        {
            "_id": "5a8596f66cc7600e089a86d5",
            "from": {
                "_id": "5a8416d6542c19147c03c53d",
                "name": "Atikilit Tera",
                "route": "NS"
            },
            "to": {
                "_id": "5a8416e2542c19147c03c53e",
                "name": "Minilik II Square",
                "route": "NS"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 945,
            "fare": 0.354375
        },
        {
            "_id": "5a85979c6cc7600e089a86d6",
            "from": {
                "_id": "5a856a87e3319923bc22383e",
                "name": "Ayat",
                "route": "EW"
            },
            "to": {
                "_id": "5a74264fc461a418b08dae07",
                "name": "Meri",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 1260,
            "fare": 0.4725
        },
        {
            "_id": "5a8597a66cc7600e089a86d7",
            "from": {
                "_id": "5a74264fc461a418b08dae07",
                "name": "Meri",
                "route": "EW"
            },
            "to": {
                "_id": "5a7455be8e130d47c86a03f6",
                "name": "CMC",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 1092,
            "fare": 0.4095
        },
        {
            "_id": "5a8597b16cc7600e089a86d8",
            "from": {
                "_id": "5a7455be8e130d47c86a03f6",
                "name": "CMC",
                "route": "EW"
            },
            "to": {
                "_id": "5a7455ec8e130d47c86a03f7",
                "name": "St Michael",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 863,
            "fare": 0.323625
        },
        {
            "_id": "5a8597ba6cc7600e089a86d9",
            "from": {
                "_id": "5a7455ec8e130d47c86a03f7",
                "name": "St Michael",
                "route": "EW"
            },
            "to": {
                "_id": "5a7456388e130d47c86a03fa",
                "name": "Civil Service College",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 860,
            "fare": 0.3225
        },
        {
            "_id": "5a8597c36cc7600e089a86da",
            "from": {
                "_id": "5a7456388e130d47c86a03fa",
                "name": "Civil Service College",
                "route": "EW"
            },
            "to": {
                "_id": "5a7dfbfd06f32e2cb8deda25",
                "name": "Management Institute",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 725,
            "fare": 0.271875
        },
        {
            "_id": "5a8597cd6cc7600e089a86db",
            "from": {
                "_id": "5a7dfbfd06f32e2cb8deda25",
                "name": "Management Institute",
                "route": "EW"
            },
            "to": {
                "_id": "5a7dff23480f3643f41dfc9f",
                "name": "Gurd Shola 1",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 970,
            "fare": 0.36375
        },
        {
            "_id": "5a8597db6cc7600e089a86dc",
            "from": {
                "_id": "5a7dff23480f3643f41dfc9f",
                "name": "Gurd Shola 1",
                "route": "EW"
            },
            "to": {
                "_id": "5a83e46c4f018d281460fb9c",
                "name": "Gurd Shola 2",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 1083,
            "fare": 0.406125
        },
        {
            "_id": "5a8597e56cc7600e089a86dd",
            "from": {
                "_id": "5a83e46c4f018d281460fb9c",
                "name": "Gurd Shola 2",
                "route": "EW"
            },
            "to": {
                "_id": "5a83e4c24f018d281460fb9d",
                "name": "Megenagna",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 804,
            "fare": 0.3015
        },
        {
            "_id": "5a8597ef6cc7600e089a86de",
            "from": {
                "_id": "5a83e4c24f018d281460fb9d",
                "name": "Megenagna",
                "route": "EW"
            },
            "to": {
                "_id": "5a83e5064f018d281460fba0",
                "name": "Lem Hotel",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 802,
            "fare": 0.30075
        },
        {
            "_id": "5a8597f86cc7600e089a86df",
            "from": {
                "_id": "5a83e5064f018d281460fba0",
                "name": "Lem Hotel",
                "route": "EW"
            },
            "to": {
                "_id": "5a83e53d4f018d281460fba2",
                "name": "Hayahulet 1",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 746,
            "fare": 0.27975
        },
        {
            "_id": "5a8598026cc7600e089a86e0",
            "from": {
                "_id": "5a83e53d4f018d281460fba2",
                "name": "Hayahulet 1",
                "route": "EW"
            },
            "to": {
                "_id": "5a83e5cdabe26a1a1c0be0b8",
                "name": "Hayahulet 2",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 770,
            "fare": 0.28875
        },
        {
            "_id": "5a85980b6cc7600e089a86e1",
            "from": {
                "_id": "5a83e5cdabe26a1a1c0be0b8",
                "name": "Hayahulet 2",
                "route": "EW"
            },
            "to": {
                "_id": "5a83e5faabe26a1a1c0be0ba",
                "name": "St Urael",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 952,
            "fare": 0.357
        },
        {
            "_id": "5a8598156cc7600e089a86e2",
            "from": {
                "_id": "5a83e5faabe26a1a1c0be0ba",
                "name": "St Urael",
                "route": "EW"
            },
            "to": {
                "_id": "5a83e61eabe26a1a1c0be0bc",
                "name": "Bambis",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 675,
            "fare": 0.253125
        },
        {
            "_id": "5a85981f6cc7600e089a86e3",
            "from": {
                "_id": "5a83e61eabe26a1a1c0be0bc",
                "name": "Bambis",
                "route": "EW"
            },
            "to": {
                "_id": "5a83e659abe26a1a1c0be0be",
                "name": "St Estifanos",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 583,
            "fare": 0.218625
        },
        {
            "_id": "5a8598296cc7600e089a86e4",
            "from": {
                "_id": "5a83e659abe26a1a1c0be0be",
                "name": "St Estifanos",
                "route": "EW"
            },
            "to": {
                "_id": "5a83e683abe26a1a1c0be0c0",
                "name": "Stadium",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 650,
            "fare": 0.24375
        },
        {
            "_id": "5a8598386cc7600e089a86e5",
            "from": {
                "_id": "5a83e683abe26a1a1c0be0c0",
                "name": "Stadium",
                "route": "EW"
            },
            "to": {
                "_id": "5a83e6ababe26a1a1c0be0c2",
                "name": "Leghar",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 435,
            "fare": 0.163125
        },
        {
            "_id": "5a8598446cc7600e089a86e6",
            "from": {
                "_id": "5a83e6ababe26a1a1c0be0c2",
                "name": "Leghar",
                "route": "EW"
            },
            "to": {
                "_id": "5a83e6d2abe26a1a1c0be0c4",
                "name": "Mexico",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 569,
            "fare": 0.213375
        },
        {
            "_id": "5a85984e6cc7600e089a86e7",
            "from": {
                "_id": "5a83e6d2abe26a1a1c0be0c4",
                "name": "Mexico",
                "route": "EW"
            },
            "to": {
                "_id": "5a83e700abe26a1a1c0be0c6",
                "name": "Tegbared",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 691,
            "fare": 0.259125
        },
        {
            "_id": "5a8598586cc7600e089a86e8",
            "from": {
                "_id": "5a83e700abe26a1a1c0be0c6",
                "name": "Tegbared",
                "route": "EW"
            },
            "to": {
                "_id": "5a83e726abe26a1a1c0be0c8",
                "name": "St Lideta",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 733,
            "fare": 0.274875
        },
        {
            "_id": "5a8598606cc7600e089a86e9",
            "from": {
                "_id": "5a83e726abe26a1a1c0be0c8",
                "name": "St Lideta",
                "route": "EW"
            },
            "to": {
                "_id": "5a83e74eabe26a1a1c0be0ca",
                "name": "Cocacola",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 725,
            "fare": 0.271875
        },
        {
            "_id": "5a85986a6cc7600e089a86ea",
            "from": {
                "_id": "5a83e74eabe26a1a1c0be0ca",
                "name": "Cocacola",
                "route": "EW"
            },
            "to": {
                "_id": "5a83e76fabe26a1a1c0be0cc",
                "name": "Torhailoch",
                "route": "EW"
            },
            "userId": {
                "_id": "5a815c1b205e0c14546476f6",
                "email": "evana.mangato@gmail.com"
            },
            "distance": 776,
            "fare": 0.291
        },
        {
            "_id": "5a92bdcfd872b0413432178f",
            "from": {
                "_id": "5a83f9cd1104c34bd8a66e71",
                "name": "kality",
                "route": "NS"
            },
            "to": {
                "_id": "5a83fa1b1104c34bd8a66e72",
                "name": "Abo Junction",
                "route": "NS"
            },
            "userId": {
                "_id": "5a8157014d99ed52700bc99f",
                "email": "ayele.gobeze@gmail.com"
            },
            "distance": 975,
            "fare": 0.365625
        }
    ]
}
  *@apiUse FareNotFoundError
  *@apiUse UnauthorizedError
  @apiUse InternalServerError
 */

 router.get('/',fareController.getAll);

 /**
  * @api {GET} /fares/paginate Paginated fares list
  * @apiName FindAllFaresAndPaginate
  * @apiGroup Fare
  * @apiDescription List all registerd fares by pagination
  * @apiVersion 0.1.0
  *
  * @apiUse FareSuccess
  *
  * @apiSuccessExample{json} Response-Success-Example
   *
   *HTTP 200 OK
   {
    "page": 1,
    "total_docs": 41,
    "total_pages": 5,
    "per_page": 10,
    "docs": [
        {
            "_id": "5a8590e0c7abd121e4b3e535",
            "from": "5a83fa1b1104c34bd8a66e72",
            "to": "5a83fa591104c34bd8a66e74",
            "userId": "5a815c1b205e0c14546476f6",
            "distance": 840,
            "fare": 0.315
        },
        {
            "_id": "5a85933d615a3a47c831f311",
            "from": "5a83fa591104c34bd8a66e74",
            "to": "5a83fa851104c34bd8a66e76",
            "userId": "5a815c1b205e0c14546476f6",
            "distance": 540,
            "fare": 0.2025
        },
        {
            "_id": "5a8593c408ea5b545c02bcb1",
            "from": "5a83fa851104c34bd8a66e76",
            "to": "5a8415aa542c19147c03c52e",
            "userId": "5a815c1b205e0c14546476f6",
            "distance": 995,
            "fare": 0.373125
        },
        {
            "_id": "5a8593ed0311323b90e037d0",
            "from": "5a8415aa542c19147c03c52e",
            "to": "5a8415c0542c19147c03c52f",
            "userId": "5a815c1b205e0c14546476f6",
            "distance": 861,
            "fare": 0.322875
        },
        {
            "_id": "5a85943d0311323b90e037d1",
            "from": "5a8415c0542c19147c03c52f",
            "to": "5a8415d5542c19147c03c530",
            "userId": "5a815c1b205e0c14546476f6",
            "distance": 1972,
            "fare": 0.7395
        },
        {
            "_id": "5a859575ab99be23d4ec1370",
            "from": "5a8415d5542c19147c03c530",
            "to": "5a8415f6542c19147c03c531",
            "userId": "5a815c1b205e0c14546476f6",
            "distance": 555,
            "fare": 0.208125
        },
        {
            "_id": "5a85959dab99be23d4ec1371",
            "from": "5a8415f6542c19147c03c531",
            "to": "5a84160a542c19147c03c532",
            "userId": "5a815c1b205e0c14546476f6",
            "distance": 610,
            "fare": 0.22875
        },
        {
            "_id": "5a8595a6ab99be23d4ec1372",
            "from": "5a84160a542c19147c03c532",
            "to": "5a84161b542c19147c03c533",
            "userId": "5a815c1b205e0c14546476f6",
            "distance": 481,
            "fare": 0.180375
        },
        {
            "_id": "5a8595b9ab99be23d4ec1373",
            "from": "5a84161b542c19147c03c533",
            "to": "5a841626542c19147c03c534",
            "userId": "5a815c1b205e0c14546476f6",
            "distance": 908,
            "fare": 0.3405
        },
        {
            "_id": "5a8595c3ab99be23d4ec1374",
            "from": "5a841626542c19147c03c534",
            "to": "5a841635542c19147c03c535",
            "userId": "5a815c1b205e0c14546476f6",
            "distance": 435,
            "fare": 0.163125
        }
    ]
}
*
   *@apiUse FareNotFoundError
   *@apiUse UnauthorizedError
   *@apiUse InternalServerError
  */

router.get('/paginate', fareController.paginate);
/**
 * @api {get} /fares/:id  Get Fare By Id
 * @apiVersion 0.1.0
 * @apiName GetFare
 * @apiGroup Fare
 * @apiPermission admin
 *
 *
 * http://localhost:5000/fares/5a478c962698af267483b1ee
 *
 *@apiDescription Retrieve fare by their Id
 * @apiParam {String} id The fare id
 *
 * @apiExample {js} Request-Example:
 * $http.defaults.headers.common["Authorization"] = token;
 * $http.get(url)
 *   .success((res, status) => doSomethingHere())
 *   .error((err, status) => doSomethingHere());
 *
 * @apiSuccess {String} _id The fare id
 * @apiSuccess {String} name The fare name
 *
 * @apiSuccessExample {json} Response-Success-Example:
  *  HTTP 200 OK
  {
   "_id": "5a8590e0c7abd121e4b3e535",
   "from": {
       "_id": "5a83fa1b1104c34bd8a66e72",
       "name": "Abo Junction"
   },
   "to": {
       "_id": "5a83fa591104c34bd8a66e74",
       "name": "Saris"
   },
   "userId": {
       "_id": "5a815c1b205e0c14546476f6",
       "email": "evana.mangato@gmail.com",
       "phone": "251-917-123456"
   },
   "distance": 840,
   "fare": 0.315
}
  *@apiUse InvalidSationIdError
  *@apiUse UnauthorizedError
  *@apiUse FareNotFoundError
  *@apiUse InternalServerError
 */
router.get('/:id', fareController.getById);

/**
 * @api {put} /fares/:id Update Fare
 * @apiName putFare
 * @apiGroup Fare
 * @apiDescription Update Fare
 * @apiVersion 0.1.0
 * @apiPermission admin
 *
 * @apiUse FareSuccess
 *
 * @apiParamExample {json} Request-Example
 *     {
 *       "id": "5a858ff72294cc4fb896e0610"
 *     }
 *
 * @apiRequestExample Request-Example
 *{
 * "fare" : 0.4095,
 * "userId" : "5a5b16fcdc3b872d0c20ac88",
 * "from" : "5a741be70449d804944dce63",
 * "to" : "5a74264fc461a418b08dae07",
 * "distance" : 1092,
 * "route" : "NS"
 *}
 *@apiSuccessExample Response-Success-Example
 *{
 *  "_id": "5a8590e0c7abd121e4b3e535",
 *  "from": "5a83fa1b1104c34bd8a66e72",
 *  "to": "5a83fa591104c34bd8a66e74",
 *  "userId": "5a815c1b205e0c14546476f6",
 *  "distance": 840,
 *  "fare": 0.315,
 *  "modifiedAt": "2018-02-28T12:35:35.488Z"
 *}
 *@apiUse UnauthorizedError
 *@apiUse InternalServerError
 */
router.put('/:id', fareController.update);
/**
 * @api {delete} /fares/:id Delete Fare
 * @apiName deleteFare
 * @apiGroup Fare
 * @apiDescription Delete fare by id
 * @apiVersion 0.1.0
 * @apiUse FareSuccess
 *
 * @apiParamExample {json} Request-Example
 *
 *     {
 *       "id": "5a96981b3993840b742ab7b5"
 *     }
 *
 *@apiSuccessExample Response-Success-Example
 *HTTP 200 OK
 * {
 * "message":"fare removed successfully",
 {
    "_id": "5a96981b3993840b742ab7b5",
    "from": "5a74264fc461a418b08dae01",
    "to": "5a7455be8e130d47c86a03f6",
    "userId": "5a8157014d99ed52700bc99f",
    "distance": 1092,
    "fare": 0.4095
}
 *@apiUse UnauthorizedError
 *@apiUse FareNotFoundError
 *@apiUse InternalServerError
 */
router.delete('/:id', fareController.delete);

router.put('/setfareamount', fareController.setFareAmount);

router.put('/setdistance',  fareController.setDistance);

router.get('/populate/:id', fareController.findAndPopulate);

router.get('/fare/price/',  fareController.getTotalPrice);

router.get('/fare/info/', fareController.completeInfo);

module.exports = router;
