apiVersion: v1
kind: Service
metadata:
  name: mobile-app-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: mobile-service
    role: mobile